name: Deploy React Vite Project
on: push
jobs:
  test-react:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci # Install all dependencies from the package-lock.json file
      - name: Run Tests
        run: npm test
  deploy:
    needs: test-react
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci # Install all dependencies from the package-lock.json file
      - name: Build Project
        run: npm run build
      - name: Deploy To Cloud
        run: echo "Deploying... "