name: Lint and Deploy React Vite Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci # Install all dependencies from the package-lock.json file
      - name: Running Linter
        run: npm run lint
  tester:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci # Install all dependencies from the package-lock.json file
      - name: Run Tests
        run: npm test
  builder:
    needs: tester
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci # Install all dependencies from the package-lock.json file
      - name: Build Website Dist Folder
        run: npm run build
      - name: Generating Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-dist-artifact
          path: dist
  deployer:
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Cloud
        run: echo "Deploying... "