name: Display Output of Issues Event
on:
  issues:
    types: [opened, edited]
jobs:
  issue-event:
    runs-on: ubuntu-latest
    steps:
      - name: Output issues event
        run: echo 'Issue-has -> ${{ toJSON(github.event.issue) }}'

